---
title: "Assignment 3 Task 4"
author: "Hanna Weyland"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

```{r, echo = TRUE, message = FALSE, warning = FALSE}
urchin_data <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names()
```

## Comparing mean size between control and annual purple sea urchins in Naples Reef in January 2010
Here, I will compare the mean sizes of purple urchins in a control and annual experiment in Naples Reef in January of 2010. 

```{r, echo = TRUE, message = FALSE, warning = FALSE}
#filter data to be purple urchin and NAPL

purple_urchin <- urchin_data %>% 
  mutate(date_new = mdy(date)) %>% 
  mutate(month_new = month(date_new)) %>% 
  mutate(year_new = year(date_new)) %>% 
  filter(common_name == "Purple Urchin", month_new == 1, year_new == 2010)
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
urchin_control <- purple_urchin %>% 
  filter(treatment == "CONTROL") %>% 
  pull(size)
mean(urchin_control)

urchin_annual <- purple_urchin %>% 
  filter(treatment == "ANNUAL") %>% 
  pull(size)
mean(urchin_annual)
```

```{r}
ggplot(data=purple_urchin, aes(x=size)) + 
  geom_histogram(bins=10) + 
  facet_wrap(~treatment) +
   labs(title = "Mean Size of Purple Urchins at Naples Reef in 2010", x= "Mean Size", y="Number of Purple Urchins")
```

```{r}
ggplot(data=purple_urchin, aes(sample=size)) + 
  geom_qq() + 
  facet_wrap(~treatment) +
   labs(title = "Mean Size of Purple Urchins at Naples Reef in 2010", x= "Mean Size", y="Number of Purple Urchins")
```













